### PR TITLE
Update runtime to 21.08

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build

**Comment by ptomato** [comment]
Thank you, appreciated! This seems fine to update, but we will have to wait until the problem with Package Control is solved (#21/#23) before merging this, or else we will push an update that will be broken due to that problem.

**Comment by ptomato** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Is it possible to merge this now?

**Comment by ptomato** [comment]
Afraid not; it will break as soon as Package Control releases a new version.

**Comment by ptomato** [comment]
I was reluctant about merging any updates to the Sublime Text flatpak since they may break if Package Control releases a new version, but it looks like they will break anyway since Package Control is releasing more regularly. So I think we can go ahead and merge this.

**Pull request merged**
